[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "<INSERT YOUR ACCOUNT IDENTIFIER>"
user = "<INSERT YOUR USERNAME>"
password = "<INSERT YOUR PASSWORD>"
