[connections.default]
warehouse = "DOC_PRACTICE_WH"
role = "SYSADMIN"
database = "FT"
schema = "DEVOPS"
account = "WOHMNNL-DOCPRACTICE.snowflakecomputing.com"
user = "NIDHYANANTHAMS"
password = "Nidhya$2025"